title: Control por RNA - RoboMaster S1
description: Proyecto 1 de Control Inteligente

theme: just-the-docs

url: "https://recandano.github.io"
baseurl: "/control-rna-robomaster"

color_scheme: light

aux_links:
  "Repositorio en GitHub":
    - "https://github.com/recandano/control-rna-robomaster"
