title: Control por RNA - RoboMaster S1
description: Proyecto 1 de Control Inteligente

theme: just-the-docs

mermaid:
  version: "10.1.0"
  
url: "https://recandano.github.io"
baseurl: "/control-rna-robomaster"

color_scheme: robomaster

aux_links:
  "Repositorio en GitHub":
    - "https://github.com/recandano/control-rna-robomaster"
